# Generated by Django 5.2.16 on 2026-08-14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("returns", "0002_demoorder_returnrequest_demo_order_demoorderitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyDemoAccount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("account_reference", models.CharField(editable=False, max_length=32)),
                ("customer_name", models.CharField(editable=False, max_length=120)),
                ("property_name", models.CharField(editable=False, max_length=120)),
                ("service_address", models.CharField(editable=False, max_length=200)),
                ("currency", models.CharField(default="USD", editable=False, max_length=3)),
                ("tariff_rate", models.DecimalField(decimal_places=4, editable=False, max_digits=8)),
                ("fixed_charge", models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ("tax_rate", models.DecimalField(decimal_places=4, editable=False, max_digits=5)),
                ("phase", models.CharField(choices=[("READING_RECEIVED", "Reading received"), ("READING_VALIDATED", "Reading validated"), ("CONSUMPTION_CALCULATED", "Consumption calculated"), ("INVOICE_ISSUED", "Invoice issued"), ("NOTIFICATION_SIMULATED", "Notification simulated")], default="READING_RECEIVED", editable=False, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visitor_session", models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name="energybil_demo", to="returns.visitorsession")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="EnergyInvoice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("invoice_number", models.CharField(editable=False, max_length=40)),
                ("period_start", models.DateField(editable=False)),
                ("period_end", models.DateField(editable=False)),
                ("due_date", models.DateField(editable=False)),
                ("consumption_kwh", models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=12)),
                ("energy_charge", models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ("tax", models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ("issued_at", models.DateTimeField(editable=False, null=True)),
                ("notification_preview", models.TextField(blank=True, editable=False)),
                ("notification_simulated_at", models.DateTimeField(editable=False, null=True)),
                ("account", models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name="invoice", to="energybil.energydemoaccount")),
            ],
        ),
        migrations.CreateModel(
            name="EnergyMeter",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("serial_number", models.CharField(editable=False, max_length=48)),
                ("label", models.CharField(editable=False, max_length=100)),
                ("previous_reading_kwh", models.DecimalField(decimal_places=3, editable=False, max_digits=12)),
                ("current_reading_kwh", models.DecimalField(decimal_places=3, editable=False, max_digits=12)),
                ("received_at", models.DateTimeField(editable=False)),
                ("account", models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name="meter", to="energybil.energydemoaccount")),
            ],
        ),
        migrations.CreateModel(
            name="EnergyWorkflowEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("phase", models.CharField(choices=[("READING_RECEIVED", "Reading received"), ("READING_VALIDATED", "Reading validated"), ("CONSUMPTION_CALCULATED", "Consumption calculated"), ("INVOICE_ISSUED", "Invoice issued"), ("NOTIFICATION_SIMULATED", "Notification simulated")], editable=False, max_length=32)),
                ("title", models.CharField(editable=False, max_length=120)),
                ("detail", models.CharField(editable=False, max_length=280)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("account", models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name="events", to="energybil.energydemoaccount")),
            ],
            options={"ordering": ("occurred_at", "id")},
        ),
        migrations.AddConstraint(model_name="energydemoaccount", constraint=models.CheckConstraint(condition=models.Q(("currency", "USD")), name="enb_account_currency_usd")),
        migrations.AddConstraint(model_name="energydemoaccount", constraint=models.CheckConstraint(condition=models.Q(("tariff_rate__gt", 0)), name="enb_account_rate_positive")),
        migrations.AddConstraint(model_name="energydemoaccount", constraint=models.CheckConstraint(condition=models.Q(("fixed_charge__gte", 0)), name="enb_account_fixed_nonneg")),
        migrations.AddConstraint(model_name="energydemoaccount", constraint=models.CheckConstraint(condition=models.Q(("tax_rate__gte", 0), ("tax_rate__lte", 1)), name="enb_account_tax_range")),
        migrations.AddConstraint(model_name="energydemoaccount", constraint=models.CheckConstraint(condition=models.Q(("phase__in", ["READING_RECEIVED", "READING_VALIDATED", "CONSUMPTION_CALCULATED", "INVOICE_ISSUED", "NOTIFICATION_SIMULATED"])), name="enb_account_phase_valid")),
        migrations.AddConstraint(model_name="energyinvoice", constraint=models.CheckConstraint(condition=models.Q(("consumption_kwh__gte", 0)), name="enb_invoice_usage_nonneg")),
        migrations.AddConstraint(model_name="energyinvoice", constraint=models.CheckConstraint(condition=models.Q(("energy_charge__gte", 0), ("subtotal__gte", 0), ("tax__gte", 0), ("total__gte", 0)), name="enb_invoice_amounts_nonneg")),
        migrations.AddConstraint(model_name="energyinvoice", constraint=models.CheckConstraint(condition=models.Q(("period_end__gte", models.F("period_start"))), name="enb_invoice_period_valid")),
        migrations.AddConstraint(model_name="energyinvoice", constraint=models.CheckConstraint(condition=models.Q(("due_date__gt", models.F("period_end"))), name="enb_invoice_due_after_period")),
        migrations.AddConstraint(model_name="energymeter", constraint=models.CheckConstraint(condition=models.Q(("previous_reading_kwh__gte", 0)), name="enb_meter_previous_nonneg")),
        migrations.AddConstraint(model_name="energymeter", constraint=models.CheckConstraint(condition=models.Q(("current_reading_kwh__gte", models.F("previous_reading_kwh"))), name="enb_meter_monotonic")),
        migrations.AddConstraint(model_name="energyworkflowevent", constraint=models.UniqueConstraint(fields=("account", "phase"), name="enb_event_unique_phase")),
        migrations.AddConstraint(model_name="energyworkflowevent", constraint=models.CheckConstraint(condition=models.Q(("phase__in", ["READING_RECEIVED", "READING_VALIDATED", "CONSUMPTION_CALCULATED", "INVOICE_ISSUED", "NOTIFICATION_SIMULATED"])), name="enb_event_phase_valid")),
    ]
