# Generated by Django 5.2.16 on 2026-07-30 20:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=20, validators=[django.core.validators.RegexValidator(message='Reference must use the RTN-000 format.', regex='^RTN-[0-9]{3,}$')])),
                ('order_reference', models.CharField(max_length=40)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NEEDS_INFORMATION', 'Needs information'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', editable=False, max_length=32)),
                ('currency', models.CharField(default='USD', editable=False, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64)),
                ('product_name', models.CharField(max_length=160)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged'), ('WRONG_ITEM', 'Wrong item'), ('NOT_AS_DESCRIBED', 'Not as described'), ('NO_LONGER_NEEDED', 'No longer needed'), ('OTHER', 'Other')], max_length=32)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_request', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnrequest')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NEEDS_INFORMATION', 'Needs information'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], editable=False, max_length=32, null=True)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NEEDS_INFORMATION', 'Needs information'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], editable=False, max_length=32)),
                ('actor', models.CharField(choices=[('CUSTOMER', 'Customer'), ('OPERATIONS', 'Operations'), ('SYSTEM', 'System')], editable=False, max_length=16)),
                ('note', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='returns.returnrequest')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(editable=False)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['expires_at'], name='ret_vis_expires_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='ret_vis_expiry_after_created')],
            },
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='visitor_session',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='returns.visitorsession'),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('PRODUCT_PHOTO', 'Product photo'), ('SERIAL_LABEL', 'Serial label'), ('RECEIPT', 'Receipt')], max_length=32)),
                ('asset_key', models.CharField(max_length=160, validators=[django.core.validators.RegexValidator(message='Asset key must be a normalized relative identifier.', regex='^[a-z0-9][a-z0-9/_.-]*$')])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_item', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='returns.returnitem')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['return_item', 'created_at'], name='ret_evid_item_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('return_item', 'asset_key'), name='ret_evid_unique_item_asset'), models.CheckConstraint(condition=models.Q(('kind__in', ['PRODUCT_PHOTO', 'SERIAL_LABEL', 'RECEIPT'])), name='ret_evid_kind_valid'), models.CheckConstraint(condition=models.Q(('asset_key', ''), _negated=True), name='ret_evid_asset_required')],
            },
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['return_request', 'created_at'], name='ret_item_req_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ret_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='ret_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['DAMAGED', 'WRONG_ITEM', 'NOT_AS_DESCRIBED', 'NO_LONGER_NEEDED', 'OTHER'])), name='ret_item_reason_valid'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sku', ''), _negated=True), models.Q(('product_name', ''), _negated=True)), name='ret_item_required_text'),
        ),
        migrations.AddIndex(
            model_name='statusevent',
            index=models.Index(fields=['return_request', 'created_at'], name='ret_event_req_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='statusevent',
            constraint=models.CheckConstraint(condition=models.Q(('from_status__isnull', True), ('from_status__in', ['DRAFT', 'SUBMITTED', 'NEEDS_INFORMATION', 'APPROVED', 'REJECTED']), _connector='OR'), name='ret_evt_from_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='statusevent',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__in', ['DRAFT', 'SUBMITTED', 'NEEDS_INFORMATION', 'APPROVED', 'REJECTED'])), name='ret_evt_to_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='statusevent',
            constraint=models.CheckConstraint(condition=models.Q(('actor__in', ['CUSTOMER', 'OPERATIONS', 'SYSTEM'])), name='ret_evt_actor_valid'),
        ),
        migrations.AddConstraint(
            model_name='statusevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_status__isnull', True), ('to_status', 'DRAFT')), models.Q(('from_status', 'DRAFT'), ('to_status', 'SUBMITTED')), models.Q(('from_status', 'SUBMITTED'), ('to_status', 'NEEDS_INFORMATION')), models.Q(('from_status', 'SUBMITTED'), ('to_status', 'APPROVED')), models.Q(('from_status', 'SUBMITTED'), ('to_status', 'REJECTED')), models.Q(('from_status', 'NEEDS_INFORMATION'), ('to_status', 'SUBMITTED')), _connector='OR'), name='ret_evt_transition_valid'),
        ),
        migrations.AddConstraint(
            model_name='statusevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor', 'SYSTEM'), ('from_status__isnull', True), ('to_status', 'DRAFT')), models.Q(('actor', 'CUSTOMER'), ('from_status', 'DRAFT'), ('to_status', 'SUBMITTED')), models.Q(('actor', 'CUSTOMER'), ('from_status', 'NEEDS_INFORMATION'), ('to_status', 'SUBMITTED')), models.Q(('actor', 'OPERATIONS'), ('from_status', 'SUBMITTED'), ('to_status__in', ('NEEDS_INFORMATION', 'APPROVED', 'REJECTED'))), _connector='OR'), name='ret_evt_actor_transition_valid'),
        ),
        migrations.AddConstraint(
            model_name='statusevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('to_status__in', ('NEEDS_INFORMATION', 'REJECTED')), _negated=True), models.Q(('note', ''), _negated=True), _connector='OR'), models.Q(models.Q(('from_status', 'NEEDS_INFORMATION'), ('to_status', 'SUBMITTED'), _negated=True), models.Q(('note', ''), _negated=True), _connector='OR')), name='ret_evt_note_required'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['visitor_session', 'status', '-updated_at'], name='ret_req_vis_status_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['visitor_session', '-created_at'], name='ret_req_vis_created_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['reference'], name='ret_req_reference_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.UniqueConstraint(fields=('visitor_session', 'reference'), name='ret_req_unique_vis_reference'),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED', 'NEEDS_INFORMATION', 'APPROVED', 'REJECTED'])), name='ret_req_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='ret_req_currency_usd'),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reference', ''), _negated=True), models.Q(('order_reference', ''), _negated=True), models.Q(('customer_name', ''), _negated=True), models.Q(('customer_email', ''), _negated=True)), name='ret_req_required_text'),
        ),
    ]
