# Generated by Django 5.2.16 on 2026-07-31 19:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_reference', models.CharField(max_length=40)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=254)),
                ('currency', models.CharField(default='USD', editable=False, max_length=3)),
                ('placed_at', models.DateTimeField(editable=False)),
                ('return_eligible', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor_session', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='demo_orders', to='returns.visitorsession')),
            ],
            options={
                'ordering': ('-placed_at', 'order_reference'),
            },
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='demo_order',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_request', to='returns.demoorder'),
        ),
        migrations.CreateModel(
            name='DemoOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64)),
                ('product_name', models.CharField(max_length=160)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demo_order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.demoorder')),
            ],
            options={
                'ordering': ('created_at', 'sku'),
            },
        ),
        migrations.AddField(
            model_name='returnitem',
            name='demo_order_item',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='returns.demoorderitem'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.UniqueConstraint(condition=models.Q(('demo_order_item__isnull', False)), fields=('return_request', 'demo_order_item'), name='ret_item_unique_order_item'),
        ),
        migrations.AddIndex(
            model_name='demoorder',
            index=models.Index(fields=['visitor_session', 'return_eligible', '-placed_at'], name='ret_order_vis_eligible_idx'),
        ),
        migrations.AddConstraint(
            model_name='demoorder',
            constraint=models.UniqueConstraint(fields=('visitor_session', 'order_reference'), name='ret_order_unique_vis_ref'),
        ),
        migrations.AddConstraint(
            model_name='demoorder',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='ret_order_currency_usd'),
        ),
        migrations.AddConstraint(
            model_name='demoorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order_reference', ''), _negated=True), models.Q(('customer_name', ''), _negated=True), models.Q(('customer_email', ''), _negated=True)), name='ret_order_required_text'),
        ),
        migrations.AddIndex(
            model_name='demoorderitem',
            index=models.Index(fields=['demo_order', 'created_at'], name='ret_order_item_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='demoorderitem',
            constraint=models.UniqueConstraint(fields=('demo_order', 'sku'), name='ret_order_item_unique_sku'),
        ),
        migrations.AddConstraint(
            model_name='demoorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ret_order_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='demoorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='ret_order_item_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='demoorderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sku', ''), _negated=True), models.Q(('product_name', ''), _negated=True)), name='ret_order_item_required_text'),
        ),
    ]
