# Generated by Django 5.2.16 on 2026-08-17 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('returns', '0002_demoorder_returnrequest_demo_order_demoorderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XmartDemoWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(editable=False, max_length=120)),
                ('project_name', models.CharField(editable=False, max_length=120)),
                ('actor_email', models.EmailField(editable=False, max_length=254)),
                ('actor_ip', models.GenericIPAddressField(editable=False, protocol='IPv4')),
                ('disclosure', models.TextField(editable=False)),
                ('phase', models.CharField(choices=[('CUSTOMER_WORKSPACE', 'Customer Workspace'), ('USER_ACCESS', 'User Access'), ('DEVICE_ASSIGNMENT', 'Device Assignment'), ('SECURITY_AUDIT', 'Security Audit'), ('WORKFLOW_COMPLETE', 'Workflow Complete')], default='CUSTOMER_WORKSPACE', editable=False, max_length=32)),
                ('users_used', models.PositiveSmallIntegerField(editable=False)),
                ('users_limit', models.PositiveSmallIntegerField(editable=False)),
                ('storage_used_gb', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('storage_limit_gb', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('imeis_used', models.PositiveSmallIntegerField(editable=False)),
                ('imeis_limit', models.PositiveSmallIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_session', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='xmart_demo', to='returns.visitorsession')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='XmartDemoUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(editable=False, max_length=254)),
                ('role', models.CharField(editable=False, max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active')], default='PENDING', editable=False, max_length=16)),
                ('seat_consumed', models.BooleanField(default=False, editable=False)),
                ('verification_resends', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('activated_at', models.DateTimeField(editable=False, null=True)),
                ('workspace', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to='xmart_demo.xmartdemoworkspace')),
            ],
        ),
        migrations.CreateModel(
            name='XmartDemoDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(editable=False, max_length=120)),
                ('synthetic_imei', models.CharField(editable=False, max_length=48)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned')], default='AVAILABLE', editable=False, max_length=16)),
                ('assigned_project', models.CharField(blank=True, editable=False, max_length=120)),
                ('assigned_at', models.DateTimeField(editable=False, null=True)),
                ('workspace', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='xmart_demo.xmartdemoworkspace')),
            ],
        ),
        migrations.CreateModel(
            name='XmartContractedModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=80)),
                ('position', models.PositiveSmallIntegerField(editable=False)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='xmart_demo.xmartdemoworkspace')),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='XmartAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField(editable=False)),
                ('phase', models.CharField(choices=[('CUSTOMER_WORKSPACE', 'Customer Workspace'), ('USER_ACCESS', 'User Access'), ('DEVICE_ASSIGNMENT', 'Device Assignment'), ('SECURITY_AUDIT', 'Security Audit'), ('WORKFLOW_COMPLETE', 'Workflow Complete')], editable=False, max_length=32)),
                ('event_type', models.CharField(choices=[('WORKSPACE_REVIEWED', 'Workspace reviewed'), ('USER_ACTIVATED', 'User activated'), ('VERIFICATION_RESENT', 'Verification resent'), ('DEVICE_ASSIGNED', 'Device assigned'), ('SECURITY_AUDIT_REVIEWED', 'Security audit reviewed'), ('WORKFLOW_COMPLETED', 'Workflow completed')], editable=False, max_length=32)),
                ('actor_email', models.EmailField(editable=False, max_length=254)),
                ('subject_reference', models.CharField(editable=False, max_length=254)),
                ('source_ip', models.GenericIPAddressField(editable=False, protocol='IPv4')),
                ('reason', models.CharField(editable=False, max_length=280)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='xmart_demo.xmartdemoworkspace')),
            ],
            options={
                'ordering': ('sequence', 'occurred_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='xmartdemoworkspace',
            constraint=models.CheckConstraint(condition=models.Q(('users_limit__gt', 0), ('users_used__lte', models.F('users_limit'))), name='xmt_ws_users_range'),
        ),
        migrations.AddConstraint(
            model_name='xmartdemoworkspace',
            constraint=models.CheckConstraint(condition=models.Q(('storage_used_gb__gte', 0), ('storage_limit_gb__gt', 0), ('storage_used_gb__lte', models.F('storage_limit_gb'))), name='xmt_ws_storage_range'),
        ),
        migrations.AddConstraint(
            model_name='xmartdemoworkspace',
            constraint=models.CheckConstraint(condition=models.Q(('imeis_limit__gt', 0), ('imeis_used__lte', models.F('imeis_limit'))), name='xmt_ws_imeis_range'),
        ),
        migrations.AddConstraint(
            model_name='xmartdemoworkspace',
            constraint=models.CheckConstraint(condition=models.Q(('phase__in', ('CUSTOMER_WORKSPACE', 'USER_ACCESS', 'DEVICE_ASSIGNMENT', 'SECURITY_AUDIT', 'WORKFLOW_COMPLETE'))), name='xmt_ws_phase_valid'),
        ),
        migrations.AddConstraint(
            model_name='xmartdemouser',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'ACTIVE'])), name='xmt_user_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='xmartdemouser',
            constraint=models.CheckConstraint(condition=models.Q(('seat_consumed', False), ('status', 'ACTIVE'), _connector='OR'), name='xmt_user_seat_active'),
        ),
        migrations.AddConstraint(
            model_name='xmartdemodevice',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['AVAILABLE', 'ASSIGNED'])), name='xmt_device_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='xmartdemodevice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_at__isnull', True), ('assigned_project', ''), ('status', 'AVAILABLE')), models.Q(('assigned_at__isnull', False), ('status', 'ASSIGNED'), models.Q(('assigned_project', ''), _negated=True)), _connector='OR'), name='xmt_device_assignment_valid'),
        ),
        migrations.AddConstraint(
            model_name='xmartcontractedmodule',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='xmt_module_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='xmartcontractedmodule',
            constraint=models.UniqueConstraint(fields=('workspace', 'position'), name='xmt_module_unique_position'),
        ),
        migrations.AddIndex(
            model_name='xmartauditevent',
            index=models.Index(fields=['workspace', 'occurred_at'], name='xmt_event_ws_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='xmartauditevent',
            constraint=models.UniqueConstraint(fields=('workspace', 'sequence'), name='xmt_event_unique_sequence'),
        ),
        migrations.AddConstraint(
            model_name='xmartauditevent',
            constraint=models.CheckConstraint(condition=models.Q(('phase__in', ('CUSTOMER_WORKSPACE', 'USER_ACCESS', 'DEVICE_ASSIGNMENT', 'SECURITY_AUDIT', 'WORKFLOW_COMPLETE'))), name='xmt_event_phase_valid'),
        ),
        migrations.AddConstraint(
            model_name='xmartauditevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['WORKSPACE_REVIEWED', 'USER_ACTIVATED', 'VERIFICATION_RESENT', 'DEVICE_ASSIGNED', 'SECURITY_AUDIT_REVIEWED', 'WORKFLOW_COMPLETED'])), name='xmt_event_type_valid'),
        ),
    ]
